<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="1" total="2" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-01-29T22:05:47 IST" name="Suite" finished-at="2023-01-29T22:06:11 IST" duration-ms="24686">
    <groups>
      <group name="Master">
        <method signature="Tc_002_Login.test_logintest()[pri:0, instance:testcases.Tc_002_Login@74fe5c40]" name="test_logintest" class="testcases.Tc_002_Login"/>
      </group> <!-- Master -->
      <group name="Sanity">
        <method signature="Tc_002_Login.test_logintest()[pri:0, instance:testcases.Tc_002_Login@74fe5c40]" name="test_logintest" class="testcases.Tc_002_Login"/>
      </group> <!-- Sanity -->
    </groups>
    <test started-at="2023-01-29T22:05:47 IST" name="chromeTest" finished-at="2023-01-29T22:06:11 IST" duration-ms="24686">
      <class name="testcases.Tc_002_Login">
        <test-method is-config="true" signature="openapp(java.lang.String)[pri:0, instance:testcases.Tc_002_Login@74fe5c40]" started-at="2023-01-29T22:05:47 IST" name="openapp" finished-at="2023-01-29T22:05:57 IST" duration-ms="9769" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openapp -->
        <test-method signature="test_logintest()[pri:0, instance:testcases.Tc_002_Login@74fe5c40]" started-at="2023-01-29T22:05:57 IST" name="test_logintest" finished-at="2023-01-29T22:06:11 IST" duration-ms="13987" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:819)
at org.testng.Assert.assertEquals(Assert.java:829)
at testcases.Tc_002_Login.test_logintest(Tc_002_Login.java:31)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_logintest -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:testcases.Tc_002_Login@74fe5c40]" started-at="2023-01-29T22:06:11 IST" name="teardown" finished-at="2023-01-29T22:06:11 IST" duration-ms="304" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- testcases.Tc_002_Login -->
    </test> <!-- chromeTest -->
  </suite> <!-- Suite -->
</testng-results>
